# Generated by Django 6.0.5 on 2026-07-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_department_name_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='office_end_time',
        ),
        migrations.RemoveField(
            model_name='company',
            name='office_start_time',
        ),
        migrations.CreateModel(
            name='OfficeTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_timings', to='organization.company')),
            ],
            options={
                'verbose_name': 'Office Timing',
                'verbose_name_plural': 'Office Timings',
                'ordering': ['shift_name'],
                'unique_together': {('company', 'shift_name')},
            },
        ),
    ]
