# Generated by Django 6.0.5 on 2026-07-20 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_company_office_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='descripion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='officetiming',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
            preserve_default=False,
        ),
    ]
