# Generated by Django 6.0.7 on 2026-08-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectteam_unique_project_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectteam',
            name='role',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('QA Engineer', 'QA Engineer'), ('DevOps Engineer', 'DevOps Engineer')], max_length=50),
        ),
    ]
