# Generated by Django 6.0.5 on 2026-07-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0003_remove_company_office_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office_timing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.officetiming'),
        ),
    ]
