# Generated by Django 6.0.5 on 2026-07-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_office_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Contract', 'Contract')], max_length=20),
        ),
    ]
