# Generated by Django 6.0.7 on 2026-08-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_reporting_manager'),
        ('organization', '0005_department_department_head_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.team'),
        ),
    ]
